### ISSUE TITLE
AttributeError: 'module' object has no attribute 'subprocess'

### ISSUE THREAD

**Issue by yagee97** [trrahul/densepose-video#1]
hi, I tried to test with video. but, the error has occurred.
i don't know reason of this error.
please explain in detail for me. thank you!

use commend
`$ python2 ~/densepose/tools/infer_simple.py --cfg ~/densepose/configs/DensePose_ResNet50_FPN_s1x-e2e.yaml --output-dir DensePoseData/infer_out/ --image-ext mp4 --wts https://s3.amazonaws.com/densepose/DensePose_ResNet50_FPN_s1x-e2e.pkl DensePoseData/demo_data/demo_video.mp4
`

<hr>
<h1> error </h1>
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
E0718 09:58:14.105464  4672 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0718 09:58:14.105479  4672 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0718 09:58:14.105482  4672 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/DensePose_ResNet50_FPN_s1x-e2e.pkl
I0718 09:58:14.783912  4672 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0718 09:58:14.788380  4672 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0718 09:58:14.789835  4672 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 8.3931e-05 secs
I0718 09:58:14.791918  4672 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0718 09:58:14.795928  4672 operator.cc:169] Engine CUDNN is not available for operator MaxPool.
I0718 09:58:14.796113  4672 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 5.9962e-05 secs
I0718 09:58:14.797823  4672 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 1.4554e-05 secs
Error opening video stream or file
Traceback (most recent call last):
  File "/home/adg/densepose/tools/infer_simple.py", line 168, in <module>
    main(args)
  File "/home/adg/densepose/tools/infer_simple.py", line 161, in main
    os.subprocess.call(
AttributeError: 'module' object has no attribute 'subprocess'

**Comment by yagee97** [comment]
I solved it! thank you

**Comment by ghost** [comment]
how :-(
