### ISSUE TITLE
No video output

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [trrahul/densepose-video#10]
Hi, 
     The program run successfully and read the video file , but at the end there is output of only last frame . (just one image , not a video output.) 
It might be due to this error  that is at the end of program. (ffmpeg: not found)

|Processing Frame 113/113 
	-Frame read in 0.001s
	 | Inference time: 0.358s
	 | im_detect_bbox: 0.096s
	 | im_detect_body_uv: 0.262s
	 | misc_bbox: 0.000s
IUV written to:  DensePoseData/infer_out/out_IUV.png
/bin/sh: 1: ffmpeg: not found

**Comment by trrahul** [comment]
Yes. You use apt to install ffmpeg.

**Comment by MuhammadAsadJaved** [comment]
I have installed ffmpeg but i get this error when i run the program again. 
it read 113/113 frames of a mp4 vidoe . but still there is not output. 

[image2 @ 0xf30200] Could find no file with path 'DensePoseData/infer_out/vid/file%02d.png' and index in the range 0-4
DensePoseData/infer_out/vid/file%02d.png: No such file or directory

**Comment by rathaROG** [comment]
> I have installed ffmpeg but i get this error when i run the program again.
> it read 113/113 frames of a mp4 vidoe . but still there is not output.
> 
> [image2 @ 0xf30200] Could find no file with path 'DensePoseData/infer_out/vid/file%02d.png' and index in the range 0-4
> DensePoseData/infer_out/vid/file%02d.png: No such file or directory

Could you please tell me how you fixed it? I tried to find the output name configuration, but it seems so complicated.
