### ISSUE TITLE
DensePose-video for Action recognition

### ISSUE THREAD

**Issue by sophia-wright-blue** [trrahul/densepose-video#7]
thank you for releasing this code, are you aware of any repos/code that uses DensePose for activity recognition?

Thanks,

**Comment by trrahul** [comment]
Sorry for the late reply. 
I do not know any project that uses DensePose. You can try OpenPose. It is production ready, unlike DensePose.

https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by sophia-wright-blue** [comment]
thanks for replying, i'm trying to combine object detection and action recognition in one model, will look into this some more
