### ISSUE TITLE
Have you try to write video via opencv?

### ISSUE THREAD

**Issue by JustinhoCHN** [trrahul/densepose-video#8]
I've tried to write frames which already transfered with texture to video using opencv, but when I defined the video encoding format as 'MJPG' like:
```
cv2.VideoWriter_fourcc(*'MJPG')
```
it'll raise error like this:
```
TypeError: Expected single character string for argument 'c1'
```
Have you met with this error?

Thanks you for your implementation.

**Comment by trrahul** [comment]
Yes, I have. I was not able to fix it, so I used ffmpeg to create video from generated frames.

**Comment by JustinhoCHN** [comment]
So we still have to save those frames to disk and then call the ffmpeg to make the video? If we do that all in memory, maybe we can save the i/o time cost. @trrahul

**Comment by trrahul** [comment]
Yes.  But i/o does not take a lot of time compared to the time taken by the inference process. It is very very less on an SSD.

**Comment by JustinhoCHN** [comment]
Got it , thanks your implementation again.
