### ISSUE TITLE
there are some thing wrong when i run this demo

### ISSUE THREAD

**Issue by Anikily** [trrahul/densepose-video#9]
|Processing Frame 35/1199 
	-Frame read in 0.001s
	 | Inference time: 0.240s
	 | im_detect_bbox: 0.191s
	 | im_detect_body_uv: 0.049s
	 | misc_bbox: 0.000s
	-Visualized in  0.330s
Traceback (most recent call last):
  File "tools/infer_vid.py", line 152, in <module>
    main(args)
  File "tools/infer_vid.py", line 139, in main
    kp_thresh=2
  File "/home/yan/densepose/detectron/utils/vis.py", line 433, in vis_one_image
    out_file = 'file%02d.png' % frame_no
TypeError: %d format: a number is required, not NoneType

the type of my video is .mp4, and i have successfully ran densepose with picture.

**Comment by linkinpark213** [comment]
I guess you need to add one parameter `frame_no=frame_no` after line 139 in `infer_vid.py`?

**Comment by Anikily** [comment]
Thanks@linkprak213,met you again dear dalao.
135             dataset=dummy_coco_dataset,
136             box_alpha=0.3,
137             show_class=False,
138             thresh=0.7,
139             kp_thresh=2
140             frame_no = frame_no
141         )
142         if ret == True:
143 
144             frame_no = frame_no +1

Do you means it?I have added the frame_no = frame_no in line140.But there happen another problem:
 File "tools/infer_vid.py", line 140
    frame_no=frame_no
           ^
SyntaxError: invalid syntax

Then ,i added it to the line143,and the original problem still exit.

**Comment by linkinpark213** [comment]
Oh you also need to add a `,` symbol after the former parameter `kp_thresh=2`... That's obvious, isn't it?

**Comment by Anikily** [comment]
Thank you@linkinpark213, I am too careless, I am so thankful to you, and then, thank you for your help to my densepose. Can i add your contact information and get to know it?_(:3JL)_

**Comment by linkinpark213** [comment]
You're welcome. My Wechat ID is the same as my Github ID. And please don't forget to close your issues after solving them :)
